### ISSUE TITLE
Theme Page / Add validation

### ISSUE THREAD

**Issue by siramsay** [chishiki/perihelion#22]
You can add a theme without a title and invalid CSS.

![Empty Theme Name](https://user-images.githubusercontent.com/16264981/125575556-54484a1b-def9-4c67-918e-69bba425e1ff.png)

- [x] Started a new branch 

https://github.com/chishiki/perihelion/tree/theme_validation
- [x] Basic Validation is working
<img width="1146" alt="Screen Shot 2021-07-14 at 3 36 58 PM" src="https://user-images.githubusercontent.com/16264981/125575287-346a54d6-0864-4fe0-9d4d-d7bd80a7e9bc.png">

**todo: note task list not complete**

- [x] Add code to Update route 
	`if ($this->urlArray[0] == 'designer' && $this->urlArray[1] == 'themes' && $this->urlArray[2] == 'update' && ctype_digit($this->urlArray[3])) {`
- [x] add translation lang()

- [x] #33
~~Advanced Issues~~
~~- [ ]Validated correct CSS~~

**Comment by siramsay** [comment]
All tasks on this Issue are complete, just need to package up and submit pull request.

**Comment by siramsay** [comment]
This is merged so closing.
